Sample/SagePayMvc.Sample/Controllers/BasketController.cs
namespace SagePayMvc.Sample.Controllers {
	using System;
	using System.Web.Mvc;
	using SagePayMvc.Sample.Models;

	public class BasketController : Controller {
		IShoppingBasket _basket;
		IProductRepository _productRepository;
		ITransactionService _transactionService;

		public BasketController(IShoppingBasket basket, IProductRepository productRepository, ITransactionService transactionService) {
			_basket = basket;
			_transactionService = transactionService;
			_productRepository = productRepository;
		}

		// Display the products currently in the shopping basket
		public ActionResult Index() {
			return View(_basket.GetItemsInBasket());
		}

		public ActionResult Add(int id) {
			var product = _productRepository.FindById(id);
			_basket.AddProduct(product);
			return RedirectToAction("Index");
		}

		public ActionResult Remove(int id) {
			_basket.RemoveItem(id);
			return RedirectToAction("Index");
		}

		public ActionResult Checkout(User user) {
			// Register the transaction with SagePay and send the user to the SagePay site.
			var transaction = _transactionService.SendTransaction(_basket, ControllerContext.RequestContext, user);
			return Redirect(transaction.NextURL);
		}
	}
}

Sample/SagePayMvc.Sample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SagePayMvc.Sample.Controllers {
	using SagePayMvc.Sample.Models;

	[HandleError]
	public class HomeController : Controller {
		IProductRepository _productRepository;

		public HomeController(IProductRepository productRepository) {
			_productRepository = productRepository;
		}

		public ActionResult Index() {
			var products = _productRepository.GetAllProducts();
			return View(products);
		}


	}
}

Sample/SagePayMvc.Sample/Views/Home/Index.cshtml
@model SagePayMvc.Sample.Models.Product[]
@{
    ViewBag.Title = "Home Page";   
}

    <p>
		This site is a small example of using SagePayMvc within an ASP.NET MVC 2 application.
    </p>
	<p>
		Click a product to add it to your shopping basket.
	</p>
	<ul>
		@foreach (var product in Model) {
			<li>@Html.ActionLink(product.Name, "Add", "Basket", new{id=product.Id},null) - @product.Price.ToString("C")</li>
		}
	</ul>